### ISSUE TITLE
tooltip  trigger:'axis' 的时候formatter里如何使用this.setState()?

### ISSUE THREAD

**Issue by kaiduo** [shifeng1993/react-native-secharts#17]
我想这样去使用他 触摸的时候拿到对应的index
constructor(props){ this.state={ index } }
let option = {
     tooltip: {
                trigger: 'axis',
                axisPointer: {
                    type: 'line',
                    lineStyle:{
                        type:'solid', 
                    }
                },
                formatter: function (params, ticket, callback) {
                     this.setState({
                         index.params[0].dataIndex 
                     })
                    return
                }
       },
 }

**Comment by shifeng1993** [comment]
你此时的this是指向formatter函数的，你应该在let option上一行，将this赋值给一个变量例如`let self = this; `，然后在 formatter函数内使用self.setState()方法，就可以了，这个问题因为不是组件问题，所以关闭，如果有组件问题，欢迎提出issues。
