### ISSUE TITLE
为什么要用webView呢，如果页面一次开多个webView，性能会很差的吧

### ISSUE THREAD

**Issue by xiang510** [shifeng1993/react-native-secharts#18]

**Comment by shifeng1993** [comment]
我们美工设计有全部是echarts图的一页的，我们测试过，即使充满两个屏幕，使用ScrollView加载，只是在真机渲染echarts过程中会稍微卡一些，如果你有需要，我可以新增一个渲染的promise，用来实现很多webview的异步加载。只是，这个意义不是很大。
