### ISSUE TITLE
加载地图不显示问题

### ISSUE THREAD

**Issue by wanshijie3** [shifeng1993/react-native-secharts#20]
请问本框架支持加载地图吗,在 
geo{
map:'china'
}
设置后并不显示地图
这种情况是暂不支持还是我设置的有问题

**Comment by shifeng1993** [comment]
地图暂时不支持吧。后面可以考虑新增特性。

**Comment by wanshijie3** [comment]
有没有大致实现方向呢,具体需要哪一块的适配修改呢?

**Comment by laoxiao79** [comment]
同问。怎样能实现中国地图加载功能。

**Comment by shifeng1993** [comment]
目前最新版本echarts4，自定义的第三方地图已经不支持，以下是官方的解释：

 ----------------------
http://echarts.baidu.com/download-map.html

ECharts 之前提供下载的矢量地图数据来自第三方，由于部分数据不符合国家《测绘法》规定，目前暂时停止下载服务。

建议大家使用以百度地图为底图的形式，参考实例：http://echarts.baidu.com/demo.html#map-polygon

----------------------

因此，我直接加入了百度地图底图，bmap。此api在react-native-secharts@1.4.3版本后有效。

欢迎大家提issues，来共同推进此组件迭代。

非常感谢以上提问题的人，谢谢！！！

**Comment by wanshijie3** [comment]
Echarts虽然官网不提供下载矢量地图了,但是网上仍然可以下载到 js 和 json 版本的地图文件,但是在使用本包装框架加载的时候仍然是不支持,尝试过修改,但是没有找到方法, 既然您使用了百度地图作为底图,可以提供个demo吗,想学习下结合本框架的具体使用方法

**Comment by shifeng1993** [comment]
这是一个官方的例子，http://echarts.baidu.com/examples/editor.html?c=lines-bmap-effect ，

这是对应的rn代码，https://github.com/shifeng1993/react-native-secharts/blob/master/example/src/pages/Map/index.js 

你可以clone下来我的源码，cd到example，跑起来例子来看效果

**Comment by hejinguo** [comment]
@shifeng1993   https://github.com/shifeng1993/react-native-secharts/blob/master/example/src/pages/Map/index.js  地图的例子不能查看呢，能补充一下新的地址链接吗？
