### ISSUE TITLE
我想请教下你是怎么加 getImage 的

### ISSUE THREAD

**Issue by youngjuning** [shifeng1993/react-native-secharts#21]

**Comment by shifeng1993** [comment]
可以查看源码中写法

**Comment by youngjuning** [comment]
你是改的 native-echarts 的吗，我把你的那个放过去，报 callback is not a  function

**Comment by shifeng1993** [comment]
是，但是改动很大，建议还是看源码。别人repo的bug我不负责修改。

**Comment by youngjuning** [comment]
ok，renderCharts 那个文件我还是看不太明白。我用这个了先

**Comment by shifeng1993** [comment]
renderCharts那个就是动态加载到webview里面的字符串，里面包含了webview到rn的传值，，toString是为了修复formatter属性为函数时的bug。
