### ISSUE TITLE
折线图label的formatter添加°符号时，模拟器查看正常，真机符号被转义

### ISSUE THREAD

**Issue by lyoo** [shifeng1993/react-native-secharts#26]
![image](https://user-images.githubusercontent.com/6435974/46667320-edb39800-cbfb-11e8-869c-76a0010e0907.png)
![image](https://user-images.githubusercontent.com/6435974/46667349-06bc4900-cbfc-11e8-8277-715b8aea6046.png)

**Comment by lir9205** [comment]
我也遇到这个问题，请问这个问题解决了吗？是怎么解决的

**Comment by lir9205** [comment]
我的解决了，我是将拼接好的字符串res做Unicode转中文：res=unescape(res.replace(/\u/g, "%u"));

**Comment by lyoo** [comment]
> 我的解决了，我是将拼接好的字符串res做Unicode转中文：res=unescape(res.replace(/\u/g, "%u"));

👍

**Comment by fantasy525** [comment]
> 我的解决了，我是将拼接好的字符串res做Unicode转中文：res=unescape(res.replace(/\u/g, "%u"));

牛皮，你怎么想到的，这种操作

**Comment by 13980519619** [comment]
我是修改y轴的提示语，这样修改后还是乱码，你们都解决了吗
