### ISSUE TITLE
echarts 的交互会影响ScrollView的交互吗

### ISSUE THREAD

**Issue by lir9205** [shifeng1993/react-native-secharts#27]
我用react-native-secharts封装了一个控件叫LabelLineChart，然后在ScrollView里面嵌套该控件，点击该控件之后，scrollView在Android端不能实现正常滚动，但是再iOS端是正常的，这个怎么解决

**Comment by shifeng1993** [comment]
可以使用一个react组件 用zIndex设置层级， 来遮盖echarts图表

**Comment by cd-butterfly** [comment]
同遇到相同问题。点击过图表后。scrollview的滚动就异常了。
