### ISSUE TITLE
使用 toolbox后   柱状图更改为折线图的问题

### ISSUE THREAD

**Issue by jahnli** [shifeng1993/react-native-secharts#32]
使用 toolbox后   将柱状图更改为折线图  但是数据刷新后 会重新变回柱状图    但是图标却显示的是折线图
![qq 20181128141614](https://user-images.githubusercontent.com/20943608/49132707-5247c500-f318-11e8-851e-d76bc931797c.png)
数据发生变化后：
![nm fvky22 8_2_53 ia h3](https://user-images.githubusercontent.com/20943608/49132719-5bd12d00-f318-11e8-86a3-8b72388926c9.png)

**Comment by shifeng1993** [comment]
现在数据刷新，直接用setState修改option的即可。


之前使用实例setoption方法，有一个问题是变更后的状态在setstate后会丢失。
