### ISSUE TITLE
xAxis 属性的axisLabel   interval函数 被屏蔽了

### ISSUE THREAD

**Issue by jahnli** [shifeng1993/react-native-secharts#33]
xAxis 属性的axisLabel   interval函数 被屏蔽   没有反应。
![image](https://user-images.githubusercontent.com/20943608/49139094-dc4d5900-f32b-11e8-93fa-5fc997974500.png)

**Comment by shifeng1993** [comment]
目前还没办法在echarts里面加 new function，和eval，这是一个已知的bug。等echarts源码研究出来地方加上吧。
