### ISSUE TITLE
ios 不刷新

### ISSUE THREAD

**Issue by 986982229** [shifeng1993/react-native-secharts#50]
react-native 0.58
option的数据绑定在reducer中，Android刷新 ios不刷新

**Comment by jsbsdbd1025** [comment]
+1

**Comment by hubingcheng** [comment]
+1

**Comment by shifeng1993** [comment]
58版本注意底层webview组件安装的版本，如果是最新，是因为webview组件修改了，包括双向通信的所有api。1.7.0版本已按最新修复
